export const GET_MOVIES_PENDING = "getMoviesPending"
export const GET_MOVIES_SUCCESS = "getMoviesSuccess"
export const GET_MOVIES_ERROR = "getMoviesError"
export const FILTER_MOVIES = "filterMovies"
export const SORT_MOVIES = "sortMovies"
export const GET_MOVIE_SUCCESS = "getMovieSuccess"
export const GET_MOVIE_BY_QUERY_SUCCESS = "getMovieByQuerySuccess"
export const BY_HIGHEST_ORDER = "highestRating"
export const BY_ADULT = "adult"

